[build]
  command = "bun install && astro check && astro build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  PUBLIC_SANITY_DATASET = "production"
  PUBLIC_SANITY_PROJECT_ID = "c526691m"
